$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/DuckDuckGo)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/SimpleGallery)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/SimpleCalender)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/priv-app/stats)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/WeatherIcons)
